clients:
  -
    name: smppsim
    systemId: smppclient1
    password: password

callback:
  scheme: http
  host: localhost
  port: 3000
  path: /automatic/bassoon/callback
  headers:
    auth-token: very-very-secret
